// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationSystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260101135454_AddAuthenticationSystem")]
    partial class AddAuthenticationSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationSystem.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_channels_notification_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_channels_status");

                    b.HasIndex("NotificationId", "Type")
                        .HasDatabaseName("ix_channels_notification_id_type");

                    b.ToTable("notification_channels", (string)null);

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.EmailChannel", b =>
                {
                    b.HasBaseType("NotificationSystem.Domain.Entities.NotificationChannel");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("IsBodyHtml")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_body_html");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("to");

                    b.HasDiscriminator().HasValue("Email");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.PushChannel", b =>
                {
                    b.HasBaseType("NotificationSystem.Domain.Entities.NotificationChannel");

                    b.Property<string>("Condition")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("condition");

                    b.Property<bool?>("ContentAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("content_available");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<bool?>("MutableContent")
                        .HasColumnType("boolean")
                        .HasColumnName("mutable_content");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int?>("TimeToLive")
                        .HasColumnType("integer")
                        .HasColumnName("time_to_live");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("to");

                    b.HasDiscriminator().HasValue("Push");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.SmsChannel", b =>
                {
                    b.HasBaseType("NotificationSystem.Domain.Entities.NotificationChannel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)")
                        .HasColumnName("message");

                    b.Property<string>("SenderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender_id");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("to");

                    b.HasDiscriminator().HasValue("Sms");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.NotificationChannel", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Entities.Notification", "Notification")
                        .WithMany("Channels")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationSystem.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationSystem.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.PushChannel", b =>
                {
                    b.OwnsOne("NotificationSystem.Domain.Entities.AndroidConfig", "Android", b1 =>
                        {
                            b1.Property<Guid>("PushChannelId");

                            b1.Property<string>("Priority")
                                .HasMaxLength(20);

                            b1.Property<string>("Ttl")
                                .HasMaxLength(20);

                            b1.HasKey("PushChannelId");

                            b1.ToTable("notification_channels");

                            b1.ToJson("android_config");

                            b1.WithOwner()
                                .HasForeignKey("PushChannelId");
                        });

                    b.OwnsOne("NotificationSystem.Domain.Entities.ApnsConfig", "Apns", b1 =>
                        {
                            b1.Property<Guid>("PushChannelId");

                            b1.Property<string>("Headers");

                            b1.HasKey("PushChannelId");

                            b1.ToTable("notification_channels");

                            b1.ToJson("apns_config");

                            b1.WithOwner()
                                .HasForeignKey("PushChannelId");
                        });

                    b.OwnsOne("NotificationSystem.Domain.Entities.NotificationContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("PushChannelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("content_body");

                            b1.Property<string>("ClickAction")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("content_click_action");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_title");

                            b1.HasKey("PushChannelId");

                            b1.ToTable("notification_channels");

                            b1.WithOwner()
                                .HasForeignKey("PushChannelId");
                        });

                    b.OwnsOne("NotificationSystem.Domain.Entities.WebpushConfig", "Webpush", b1 =>
                        {
                            b1.Property<Guid>("PushChannelId");

                            b1.Property<string>("Headers");

                            b1.HasKey("PushChannelId");

                            b1.ToTable("notification_channels");

                            b1.ToJson("webpush_config");

                            b1.WithOwner()
                                .HasForeignKey("PushChannelId");
                        });

                    b.Navigation("Android");

                    b.Navigation("Apns");

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Webpush");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
